### ISSUE TITLE
Does this work only on Debian?

### ISSUE THREAD

**Issue by smj4490** [alestic/ec2-expire-snapshots#13]
I'd like to use this on a work project but all of the work boxes run CentOS, would this work on CentOS or would I have to tweak the code for it to play nice with CentOS? This repo looks to be built specifically for a Debian environment unless I'm mistaken.

**Comment by FernandoMiguel** [comment]
Hi.
Even with the dependencies that @dansmith65 mentioned, I get an error:
Can't locate Date/Manip.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./ec2-expire-snapshots line 10.
BEGIN failed--compilation aborted at ./ec2-expire-snapshots line 10.

i had to install perl-DateTime-Format-ISO8601 perl-DateTime perl-Date-Manip

**Comment by galambalazs** [comment]
Here is how I got it *working* on CentOS 7

```
sudo yum install -y wget git perl perl-CPAN 

# Grab everything that's available from EPEL 7
# see packages here: https://dl.fedoraproject.org/pub/epel/7/x86_64/repoview/letter_p.group.html
sudo yum install --enablerepo=epel -y perl-Date-Manip perl-DateTime perl-DateTime-TimeZone perl-DateTime-Format-ISO8601
sudo yum install --enablerepo=epel -y perl-File-Slurp perl-Net-SSLeay perl-IO-Socket-SSL perl-Time-HiRes perl-Params-Validate ca-certificates  perl-Net-Amazon-EC2 

#  Net::Amazon::EC2 is the only one not available on EPEL for CentOS 7
# So we grab it from cpan
# needs: Net::Amazon::EC2 -> XML::Simple -> XML::Parser -> XML::SAX::Expat -> expat-devel
sudo yum install -y expat-devel
sudo cpan App::cpanminus  # a better package manager
sudo /usr/local/bin/cpanm Net::Amazon::EC2
```

Try it out (shouldn't complain about missing libraries):

```
git clone https://github.com/alestic/ec2-expire-snapshots.git ~/ec2-expire-snapshots
cd ~/ec2-expire-snapshots
./ec2-expire-snapshots --noaction
```

**Comment by galambalazs** [comment]
Added wiki page:
https://github.com/alestic/ec2-expire-snapshots/wiki/Installing-on-CentOS-or-RHEL-(yum)

Also PR to include in the README
https://github.com/alestic/ec2-expire-snapshots/pull/28
