### ISSUE TITLE
ec2-expire-snapshots_0.13 fails to upgrade on Ubuntu 10.04.4 LTS

### ISSUE THREAD

**Issue by ovidiumpp** [alestic/ec2-expire-snapshots#17]
I would like to upgrade to latest ec2-expire-snapshots 0.13 via Alestic PPA and the upgrade fails:

Preparing to replace ec2-expire-snapshots 0.12 (using .../ec2-expire-snapshots_0.13_all.deb) ...
Unpacking replacement ec2-expire-snapshots ...
dpkg-deb: file `/var/cache/apt/archives/ec2-expire-snapshots_0.13_all.deb' contains ununderstood data member data.tar.xz     , giving up
dpkg: error processing /var/cache/apt/archives/ec2-expire-snapshots_0.13_all.deb (--unpack):
 subprocess dpkg-deb --fsys-tarfile returned error exit status 2
Processing triggers for man-db ...
Errors were encountered while processing:
 /var/cache/apt/archives/ec2-expire-snapshots_0.13_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ehammond** [comment]
I don't run Ubuntu 10.04 any more, so am probably not going to be able to reproduce or solve this.

Fixes welcomed.

**Comment by ehammond** [comment]
I guess Ubuntu 10.04 will be unsupported until somebody provides a patch.
