### ISSUE TITLE
Filter parameter fails validation when expiring snapshots

### ISSUE THREAD

**Issue by justinpincar** [alestic/ec2-expire-snapshots#19]
Version: 0.13. Works fine in version 0.12 but the package was removed from the repo.

```
root@ip-172-31-54-229:~# ec2-expire-snapshots -d vol-XXXXXXXX
ec2-expire-snapshots: Using AWS access key: YYYYYYYYYYYY
ec2-expire-snapshots: Retrieving snapshot list
ec2-expire-snapshots: ERROR: describe_snapshots: The following parameter was passed in the call to Net::Amazon::EC2::describe_snapshots but was not listed in the validation options: Filter
 at /usr/share/perl5/Net/Amazon/EC2.pm line 2251
        Net::Amazon::EC2::describe_snapshots(undef, 'Filter', 'ARRAY(0x4487508)') called at /usr/bin/ec2-expire-snapshots line 183
        eval {...} called at /usr/bin/ec2-expire-snapshots line 182
        main::snapshots_for_volumes('Net::Amazon::EC2=HASH(0x3b43000)', undef, 'vol-XXXXXXXX') called at /usr/bin/ec2-expire-snapshots line 120
```

**Comment by ehammond** [comment]
Thanks for reporting this. Can you provide a bit more detail about what software combination causes this error?

What software are you talking about that is version 0.12 and 0.13?
What is the version of ec2-expire-snapshots?
What is the version of Net::Amazon::EC2?
What Linux distro and release are you using?

Are you still experiencing this error with the latest versions of the software?

**Comment by justinpincar** [comment]
Hmmm I ended up fixing this by upgrading something but I don't remember what... thanks for the response though.

**Comment by ehammond** [comment]
Henri Roussez switched the source to use the Filter option a while back. I'm guessing that requires a more recent version of Net::Amazon::EC2.

Thanks for following up.
