### ISSUE TITLE
snapshots is inUse

### ISSUE THREAD

**Issue by ghost** [alestic/ec2-expire-snapshots#3]
If snapshot is InUse by ami, the script is die and other snapshots arent deleted. For example I need keep last 3 days snapshots, but script stop on error and other snapshots arent cleaned: 

InvalidSnapshot.InUse: The snapshot snap-234224 is currently in use by ami-436f64ba at /opt/ebs_snapshots/ec2-expire-snapshots line 221.

**Comment by ehammond** [comment]
Thanks for doing the work and for submitting this.

I don't think we need to make it as complicated as an option. I would like to see it simply skip any snapshot that is in use with an informational message like the one you list.

**Comment by ehammond** [comment]
This should be fixed by #24.
