### ISSUE TITLE
The script hangs for quite a long time (about 15 minutes.)

### ISSUE THREAD

**Issue by varunwy** [alestic/ec2-expire-snapshots#6]
I have two Amazon EC2 instances. One having Ubuntu (Kernel 2.6.32-318) and the other is having Amazo Linux (Kernel 3.4.37-40.44). Both have similar hardware configuration. The script executes in about 10 seconds on Ubuntu machine but on the Amazon Linux instance it takes 10 to 15 minutes to complete. On the Amazon Linux instance I debugged and found that it waits on the line:

eval {
        $snapshots = $ec2->describe_snapshots();
    };

I have the package aws-apitools-ec2.noarch version 1.6.7.2 installed on the Amazon Linux machine. Can someone please point me to what's going on here? Why the describe_snapshots command takes so... long on the Amazon Linux instance and finishes in a few seconds on the Ubuntu instance.

**Comment by ehammond** [comment]
I believe this issue has been improved in a more recent version of ec2-expire-snapshots.

Please test with the latest version and re-open if you are still experiencing problems.
